services:
          - type: web
            name: bookstore-backend
            env: node
            region: oregon
            buildCommand: npm run build
            startCommand: npm start
            envVars:
                      - key: NPM_CONFIG_INCLUDE
                        value: dev
                      - key: NODE_ENV
                        value: production
